---
path: github.com/mediocregopher/gobdns
deps:
    - loc: github.com/miekg/dns
    - loc: github.com/mediocregopher/flagconfig
    - loc: github.com/jteeuwen/go-bindata
    - loc: github.com/elazarl/go-bindata-assetfs
